discord:
    token: DISCORD_TOKEN
    server_id: 'DISCORD_SERVER_ID'
rate_limit:
    message_limit: 3
    cooldown_seconds: 30
twitch:
    api_key: TWITCH_API_KEY
    streamers:
    - STREAMER_NAME
    - STREAMER_NAME
    - STREAMER_NAME
